# app name
APPLICATION = arduino_custom

# Set board to arduino-uno
BOARD ?= arduino-uno

# RIOT directory
RIOTBASE ?= $(CURDIR)/../..

USEMODULE += arduino

# Debugging
DEVELHELP ?= 1

# Change this to 0 show compiler invocation lines by default:
QUIET ?= 1

include $(RIOTBASE)/Makefile.include
